[2021-04-09 09:00:54 -0300] [383578] [INFO] Starting gunicorn 20.1.0
[2021-04-09 09:00:54 -0300] [383578] [INFO] Listening at: unix:/home/wagneroliveira/PycharmProjects/blogIntrospect/blogIntrospect.sock (383578)
[2021-04-09 09:00:54 -0300] [383578] [INFO] Using worker: sync
[2021-04-09 09:00:54 -0300] [383580] [INFO] Booting worker with pid: 383580
[2021-04-09 09:00:54 -0300] [383581] [INFO] Booting worker with pid: 383581
[2021-04-09 09:00:54 -0300] [383582] [INFO] Booting worker with pid: 383582
[2021-04-09 09:00:54 -0300] [383580] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/wagneroliveira/PycharmProjects/blogIntrospect/blogIntrospect/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/django/conf/__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/django/conf/__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'sample-app'
[2021-04-09 09:00:54 -0300] [383581] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/wagneroliveira/PycharmProjects/blogIntrospect/blogIntrospect/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/django/conf/__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/django/conf/__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'sample-app'
[2021-04-09 09:00:54 -0300] [383580] [INFO] Worker exiting (pid: 383580)
[2021-04-09 09:00:54 -0300] [383581] [INFO] Worker exiting (pid: 383581)
[2021-04-09 09:00:54 -0300] [383582] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/wagneroliveira/PycharmProjects/blogIntrospect/blogIntrospect/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/django/conf/__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/django/conf/__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'sample-app'
[2021-04-09 09:00:54 -0300] [383582] [INFO] Worker exiting (pid: 383582)
[2021-04-09 09:00:54 -0300] [383578] [WARNING] Worker with pid 383580 was terminated due to signal 15
[2021-04-09 09:00:54 -0300] [383578] [WARNING] Worker with pid 383582 was terminated due to signal 15
[2021-04-09 09:00:54 -0300] [383578] [INFO] Shutting down: Master
[2021-04-09 09:00:54 -0300] [383578] [INFO] Reason: Worker failed to boot.
[2021-04-09 09:00:55 -0300] [383585] [INFO] Starting gunicorn 20.1.0
[2021-04-09 09:00:55 -0300] [383585] [INFO] Listening at: unix:/home/wagneroliveira/PycharmProjects/blogIntrospect/blogIntrospect.sock (383585)
[2021-04-09 09:00:55 -0300] [383585] [INFO] Using worker: sync
[2021-04-09 09:00:55 -0300] [383587] [INFO] Booting worker with pid: 383587
[2021-04-09 09:00:55 -0300] [383588] [INFO] Booting worker with pid: 383588
[2021-04-09 09:00:55 -0300] [383589] [INFO] Booting worker with pid: 383589
[2021-04-09 09:00:55 -0300] [383587] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/wagneroliveira/PycharmProjects/blogIntrospect/blogIntrospect/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/django/conf/__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/django/conf/__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'sample-app'
[2021-04-09 09:00:55 -0300] [383587] [INFO] Worker exiting (pid: 383587)
[2021-04-09 09:00:55 -0300] [383588] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/wagneroliveira/PycharmProjects/blogIntrospect/blogIntrospect/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/django/conf/__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/django/conf/__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'sample-app'
[2021-04-09 09:00:55 -0300] [383588] [INFO] Worker exiting (pid: 383588)
[2021-04-09 09:00:55 -0300] [383589] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/wagneroliveira/PycharmProjects/blogIntrospect/blogIntrospect/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/django/conf/__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/django/conf/__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'sample-app'
[2021-04-09 09:00:55 -0300] [383589] [INFO] Worker exiting (pid: 383589)
Traceback (most recent call last):
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/arbiter.py", line 209, in run
    self.sleep()
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/arbiter.py", line 357, in sleep
    ready = select.select([self.PIPE[0]], [], [], 1.0)
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/bin/gunicorn", line 33, in <module>
    sys.exit(load_entry_point('gunicorn==20.1.0', 'console_scripts', 'gunicorn')())
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 67, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/app/base.py", line 231, in run
    super().run()
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/arbiter.py", line 229, in run
    self.halt(reason=inst.reason, exit_status=inst.exit_status)
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/arbiter.py", line 342, in halt
    self.stop()
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/arbiter.py", line 393, in stop
    time.sleep(0.1)
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
[2021-04-09 09:00:58 -0300] [383590] [INFO] Starting gunicorn 20.1.0
[2021-04-09 09:00:58 -0300] [383590] [INFO] Listening at: unix:/home/wagneroliveira/PycharmProjects/blogIntrospect/blogIntrospect.sock (383590)
[2021-04-09 09:00:58 -0300] [383590] [INFO] Using worker: sync
[2021-04-09 09:00:58 -0300] [383592] [INFO] Booting worker with pid: 383592
[2021-04-09 09:00:58 -0300] [383593] [INFO] Booting worker with pid: 383593
[2021-04-09 09:00:58 -0300] [383592] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/wagneroliveira/PycharmProjects/blogIntrospect/blogIntrospect/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/django/conf/__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/django/conf/__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'sample-app'
[2021-04-09 09:00:58 -0300] [383592] [INFO] Worker exiting (pid: 383592)
[2021-04-09 09:00:58 -0300] [383593] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/wagneroliveira/PycharmProjects/blogIntrospect/blogIntrospect/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/django/conf/__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/django/conf/__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'sample-app'
[2021-04-09 09:00:58 -0300] [383593] [INFO] Worker exiting (pid: 383593)
Traceback (most recent call last):
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/arbiter.py", line 202, in run
    self.manage_workers()
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/arbiter.py", line 551, in manage_workers
    self.spawn_workers()
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/arbiter.py", line 623, in spawn_workers
    time.sleep(0.1 * random.random())
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/bin/gunicorn", line 33, in <module>
    sys.exit(load_entry_point('gunicorn==20.1.0', 'console_scripts', 'gunicorn')())
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 67, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/app/base.py", line 231, in run
    super().run()
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/arbiter.py", line 229, in run
    self.halt(reason=inst.reason, exit_status=inst.exit_status)
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/arbiter.py", line 342, in halt
    self.stop()
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/arbiter.py", line 393, in stop
    time.sleep(0.1)
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
[2021-04-09 09:01:01 -0300] [383600] [INFO] Starting gunicorn 20.1.0
[2021-04-09 09:01:01 -0300] [383600] [INFO] Listening at: unix:/home/wagneroliveira/PycharmProjects/blogIntrospect/blogIntrospect.sock (383600)
[2021-04-09 09:01:01 -0300] [383600] [INFO] Using worker: sync
[2021-04-09 09:01:01 -0300] [383602] [INFO] Booting worker with pid: 383602
[2021-04-09 09:01:01 -0300] [383603] [INFO] Booting worker with pid: 383603
[2021-04-09 09:01:01 -0300] [383604] [INFO] Booting worker with pid: 383604
[2021-04-09 09:01:01 -0300] [383602] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/wagneroliveira/PycharmProjects/blogIntrospect/blogIntrospect/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/django/conf/__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/django/conf/__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'sample-app'
[2021-04-09 09:01:01 -0300] [383602] [INFO] Worker exiting (pid: 383602)
[2021-04-09 09:01:01 -0300] [383604] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/wagneroliveira/PycharmProjects/blogIntrospect/blogIntrospect/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/django/conf/__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/django/conf/__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'sample-app'
[2021-04-09 09:01:01 -0300] [383604] [INFO] Worker exiting (pid: 383604)
[2021-04-09 09:01:01 -0300] [383600] [WARNING] Worker with pid 383604 was terminated due to signal 15
[2021-04-09 09:01:01 -0300] [383603] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/wagneroliveira/PycharmProjects/blogIntrospect/blogIntrospect/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/django/conf/__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/django/conf/__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'sample-app'
[2021-04-09 09:01:01 -0300] [383603] [INFO] Worker exiting (pid: 383603)
Traceback (most recent call last):
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/arbiter.py", line 209, in run
    self.sleep()
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/arbiter.py", line 357, in sleep
    ready = select.select([self.PIPE[0]], [], [], 1.0)
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/bin/gunicorn", line 33, in <module>
    sys.exit(load_entry_point('gunicorn==20.1.0', 'console_scripts', 'gunicorn')())
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 67, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/app/base.py", line 231, in run
    super().run()
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/arbiter.py", line 229, in run
    self.halt(reason=inst.reason, exit_status=inst.exit_status)
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/arbiter.py", line 342, in halt
    self.stop()
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/arbiter.py", line 393, in stop
    time.sleep(0.1)
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/home/wagneroliveira/.virtualenvs/blogIntrospect/lib/python3.8/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
[2021-04-09 09:05:31 -0300] [383878] [INFO] Starting gunicorn 20.1.0
[2021-04-09 09:05:31 -0300] [383878] [INFO] Listening at: unix:/home/wagneroliveira/PycharmProjects/blogIntrospect/blogIntrospect.sock (383878)
[2021-04-09 09:05:31 -0300] [383878] [INFO] Using worker: sync
[2021-04-09 09:05:31 -0300] [383880] [INFO] Booting worker with pid: 383880
[2021-04-09 09:05:31 -0300] [383881] [INFO] Booting worker with pid: 383881
[2021-04-09 09:05:31 -0300] [383882] [INFO] Booting worker with pid: 383882
 - - [09/Apr/2021:09:12:35 -0300] "GET / HTTP/1.0" 200 7427 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.152 Safari/537.36"
 - - [09/Apr/2021:09:12:36 -0300] "GET /favicon.ico HTTP/1.0" 404 179 "http://blogintrospect.com/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.152 Safari/537.36"
 - - [09/Apr/2021:09:12:39 -0300] "GET / HTTP/1.0" 200 7427 "http://blogintrospect.com/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.152 Safari/537.36"
 - - [09/Apr/2021:09:12:41 -0300] "GET /blog/ HTTP/1.0" 200 5310 "http://blogintrospect.com/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.152 Safari/537.36"
 - - [09/Apr/2021:09:12:45 -0300] "GET /elements/ HTTP/1.0" 200 17158 "http://blogintrospect.com/blog/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.152 Safari/537.36"
 - - [09/Apr/2021:09:12:47 -0300] "GET / HTTP/1.0" 200 7427 "http://blogintrospect.com/elements/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.152 Safari/537.36"
 - - [09/Apr/2021:09:13:22 -0300] "GET / HTTP/1.0" 200 7427 "http://blogintrospect.com/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.152 Safari/537.36"
[2021-04-09 09:15:17 -0300] [383878] [INFO] Handling signal: term
[2021-04-09 09:15:17 -0300] [383882] [INFO] Worker exiting (pid: 383882)
[2021-04-09 09:15:17 -0300] [383880] [INFO] Worker exiting (pid: 383880)
[2021-04-09 09:15:17 -0300] [383881] [INFO] Worker exiting (pid: 383881)
[2021-04-09 09:15:17 -0300] [383878] [INFO] Shutting down: Master
[2021-04-09 09:16:06 -0300] [384728] [INFO] Starting gunicorn 20.1.0
[2021-04-09 09:16:06 -0300] [384728] [INFO] Listening at: unix:/home/wagneroliveira/PycharmProjects/blogIntrospect/blogIntrospect.sock (384728)
[2021-04-09 09:16:06 -0300] [384728] [INFO] Using worker: sync
[2021-04-09 09:16:06 -0300] [384730] [INFO] Booting worker with pid: 384730
[2021-04-09 09:16:06 -0300] [384733] [INFO] Booting worker with pid: 384733
[2021-04-09 09:16:06 -0300] [384734] [INFO] Booting worker with pid: 384734
 - - [09/Apr/2021:09:16:27 -0300] "GET / HTTP/1.0" 200 7427 "http://blogintrospect.com/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.152 Safari/537.36"
 - - [09/Apr/2021:09:16:30 -0300] "GET / HTTP/1.0" 200 7427 "http://blogintrospect.com/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.152 Safari/537.36"
 - - [09/Apr/2021:09:16:31 -0300] "GET /blog/ HTTP/1.0" 200 5310 "http://blogintrospect.com/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.152 Safari/537.36"
 - - [09/Apr/2021:09:16:32 -0300] "GET /elements/ HTTP/1.0" 200 17158 "http://blogintrospect.com/blog/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.152 Safari/537.36"
 - - [09/Apr/2021:09:16:33 -0300] "GET / HTTP/1.0" 200 7427 "http://blogintrospect.com/elements/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.152 Safari/537.36"
 - - [09/Apr/2021:09:17:25 -0300] "GET / HTTP/1.0" 200 7427 "http://blogintrospect.com/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.152 Safari/537.36"
 - - [09/Apr/2021:09:17:39 -0300] "GET /quemsou/ HTTP/1.0" 200 6159 "http://blogintrospect.com/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.152 Safari/537.36"
 - - [09/Apr/2021:09:17:58 -0300] "GET /blog/ HTTP/1.0" 200 5310 "http://blogintrospect.com/quemsou/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.152 Safari/537.36"
 - - [09/Apr/2021:09:18:43 -0300] "GET / HTTP/1.0" 200 7427 "http://blogintrospect.com/quemsou/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.152 Safari/537.36"
 - - [09/Apr/2021:09:18:44 -0300] "GET / HTTP/1.0" 200 7427 "http://blogintrospect.com/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.152 Safari/537.36"
 - - [09/Apr/2021:09:18:46 -0300] "GET /blog/ HTTP/1.0" 200 5310 "http://blogintrospect.com/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.152 Safari/537.36"
 - - [09/Apr/2021:09:19:07 -0300] "GET / HTTP/1.0" 200 7427 "http://blogintrospect.com/blog/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.152 Safari/537.36"
[2021-04-09 09:20:22 -0300] [384728] [INFO] Handling signal: term
[2021-04-09 09:20:22 -0300] [384733] [INFO] Worker exiting (pid: 384733)
[2021-04-09 09:20:22 -0300] [384730] [INFO] Worker exiting (pid: 384730)
[2021-04-09 09:20:22 -0300] [384734] [INFO] Worker exiting (pid: 384734)
[2021-04-09 09:20:22 -0300] [384728] [INFO] Shutting down: Master
[2021-04-09 09:20:23 -0300] [385104] [INFO] Starting gunicorn 20.1.0
[2021-04-09 09:20:23 -0300] [385104] [INFO] Listening at: unix:/home/wagneroliveira/PycharmProjects/blogIntrospect/blogIntrospect.sock (385104)
[2021-04-09 09:20:23 -0300] [385104] [INFO] Using worker: sync
[2021-04-09 09:20:23 -0300] [385106] [INFO] Booting worker with pid: 385106
[2021-04-09 09:20:23 -0300] [385107] [INFO] Booting worker with pid: 385107
[2021-04-09 09:20:39 -0300] [385104] [INFO] Handling signal: term
[2021-04-09 09:20:39 -0300] [385106] [INFO] Worker exiting (pid: 385106)
[2021-04-09 09:20:39 -0300] [385107] [INFO] Worker exiting (pid: 385107)
[2021-04-09 09:20:40 -0300] [385104] [INFO] Shutting down: Master
[2021-04-09 09:20:50 -0300] [385185] [INFO] Starting gunicorn 20.1.0
[2021-04-09 09:20:50 -0300] [385185] [INFO] Listening at: unix:/home/wagneroliveira/PycharmProjects/blogIntrospect/blogIntrospect.sock (385185)
[2021-04-09 09:20:50 -0300] [385185] [INFO] Using worker: sync
[2021-04-09 09:20:50 -0300] [385187] [INFO] Booting worker with pid: 385187
[2021-04-09 09:20:50 -0300] [385188] [INFO] Booting worker with pid: 385188
[2021-04-09 09:21:12 -0300] [385185] [INFO] Handling signal: term
[2021-04-09 09:21:12 -0300] [385187] [INFO] Worker exiting (pid: 385187)
[2021-04-09 09:21:12 -0300] [385188] [INFO] Worker exiting (pid: 385188)
[2021-04-09 09:21:12 -0300] [385185] [INFO] Shutting down: Master
[2021-04-09 09:21:44 -0300] [385288] [INFO] Starting gunicorn 20.1.0
[2021-04-09 09:21:44 -0300] [385288] [INFO] Listening at: unix:/home/wagneroliveira/PycharmProjects/blogIntrospect/blogIntrospect.sock (385288)
[2021-04-09 09:21:44 -0300] [385288] [INFO] Using worker: sync
[2021-04-09 09:21:44 -0300] [385290] [INFO] Booting worker with pid: 385290
[2021-04-09 09:21:44 -0300] [385291] [INFO] Booting worker with pid: 385291
 - - [09/Apr/2021:09:21:57 -0300] "GET / HTTP/1.0" 200 7427 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.152 Safari/537.36"
 - - [09/Apr/2021:09:22:12 -0300] "GET /quemsou/ HTTP/1.0" 200 6159 "http://blogintrospect.com/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.152 Safari/537.36"
 - - [09/Apr/2021:09:22:59 -0300] "GET / HTTP/1.0" 200 7427 "http://blogintrospect.com/quemsou/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.152 Safari/537.36"
[2021-04-09 09:30:28 -0300] [385288] [INFO] Handling signal: term
[2021-04-09 09:30:28 -0300] [385291] [INFO] Worker exiting (pid: 385291)
[2021-04-09 09:30:28 -0300] [385290] [INFO] Worker exiting (pid: 385290)
[2021-04-09 09:30:28 -0300] [385288] [INFO] Shutting down: Master
[2021-04-09 09:31:41 -0300] [385853] [INFO] Starting gunicorn 20.1.0
[2021-04-09 09:31:41 -0300] [385853] [INFO] Listening at: unix:/home/wagneroliveira/PycharmProjects/blogIntrospect/blogIntrospect.sock (385853)
[2021-04-09 09:31:41 -0300] [385853] [INFO] Using worker: sync
[2021-04-09 09:31:41 -0300] [385856] [INFO] Booting worker with pid: 385856
[2021-04-09 09:31:41 -0300] [385857] [INFO] Booting worker with pid: 385857
[2021-04-09 11:53:46 -0300] [1914] [INFO] Starting gunicorn 20.1.0
[2021-04-09 11:53:46 -0300] [1914] [INFO] Listening at: unix:/home/wagneroliveira/PycharmProjects/blogIntrospect/blogIntrospect.sock (1914)
[2021-04-09 11:53:46 -0300] [1914] [INFO] Using worker: sync
[2021-04-09 11:53:46 -0300] [1943] [INFO] Booting worker with pid: 1943
[2021-04-09 11:53:46 -0300] [1945] [INFO] Booting worker with pid: 1945
[2021-04-11 10:54:15 -0300] [1914] [INFO] Handling signal: term
[2021-04-11 10:54:15 -0300] [1945] [INFO] Worker exiting (pid: 1945)
[2021-04-11 10:54:15 -0300] [1943] [INFO] Worker exiting (pid: 1943)
[2021-04-11 10:54:16 -0300] [1914] [INFO] Shutting down: Master
[2021-04-11 10:55:21 -0300] [1889] [INFO] Starting gunicorn 20.1.0
[2021-04-11 10:55:21 -0300] [1889] [INFO] Listening at: unix:/home/wagneroliveira/PycharmProjects/blogIntrospect/blogIntrospect.sock (1889)
[2021-04-11 10:55:21 -0300] [1889] [INFO] Using worker: sync
[2021-04-11 10:55:21 -0300] [1928] [INFO] Booting worker with pid: 1928
[2021-04-11 10:55:21 -0300] [1941] [INFO] Booting worker with pid: 1941
[2021-04-13 10:36:22 -0300] [1900] [INFO] Starting gunicorn 20.1.0
[2021-04-13 10:36:22 -0300] [1900] [INFO] Listening at: unix:/home/wagneroliveira/PycharmProjects/blogIntrospect/blogIntrospect.sock (1900)
[2021-04-13 10:36:22 -0300] [1900] [INFO] Using worker: sync
[2021-04-13 10:36:22 -0300] [1980] [INFO] Booting worker with pid: 1980
[2021-04-13 10:36:22 -0300] [1984] [INFO] Booting worker with pid: 1984
[2021-04-22 09:28:04 -0300] [1921] [INFO] Starting gunicorn 20.1.0
[2021-04-22 09:28:04 -0300] [1921] [INFO] Listening at: unix:/home/wagneroliveira/PycharmProjects/blogIntrospect/blogIntrospect.sock (1921)
[2021-04-22 09:28:04 -0300] [1921] [INFO] Using worker: sync
[2021-04-22 09:28:04 -0300] [1991] [INFO] Booting worker with pid: 1991
[2021-04-22 09:28:04 -0300] [1999] [INFO] Booting worker with pid: 1999
[2021-04-28 17:01:53 -0300] [1921] [INFO] Handling signal: term
[2021-04-28 17:01:53 -0300] [1991] [INFO] Worker exiting (pid: 1991)
[2021-04-28 17:01:53 -0300] [1999] [INFO] Worker exiting (pid: 1999)
[2021-04-28 17:01:54 -0300] [1921] [INFO] Shutting down: Master
[2021-04-28 17:03:56 -0300] [1898] [INFO] Starting gunicorn 20.1.0
[2021-04-28 17:03:56 -0300] [1898] [INFO] Listening at: unix:/home/wagneroliveira/PycharmProjects/blogIntrospect/blogIntrospect.sock (1898)
[2021-04-28 17:03:56 -0300] [1898] [INFO] Using worker: sync
[2021-04-28 17:03:56 -0300] [1974] [INFO] Booting worker with pid: 1974
[2021-04-28 17:03:56 -0300] [1980] [INFO] Booting worker with pid: 1980
[2021-04-29 07:47:39 -0300] [1910] [INFO] Starting gunicorn 20.1.0
[2021-04-29 07:47:39 -0300] [1910] [INFO] Listening at: unix:/home/wagneroliveira/PycharmProjects/blogIntrospect/blogIntrospect.sock (1910)
[2021-04-29 07:47:39 -0300] [1910] [INFO] Using worker: sync
[2021-04-29 07:47:39 -0300] [1985] [INFO] Booting worker with pid: 1985
[2021-04-29 07:47:39 -0300] [1988] [INFO] Booting worker with pid: 1988
[2021-05-10 19:51:11 -0300] [1882] [INFO] Starting gunicorn 20.1.0
[2021-05-10 19:51:11 -0300] [1882] [INFO] Listening at: unix:/home/wagneroliveira/PycharmProjects/blogIntrospect/blogIntrospect.sock (1882)
[2021-05-10 19:51:11 -0300] [1882] [INFO] Using worker: sync
[2021-05-10 19:51:11 -0300] [1886] [INFO] Booting worker with pid: 1886
[2021-05-10 19:51:11 -0300] [1889] [INFO] Booting worker with pid: 1889
[2021-05-14 07:22:50 -0300] [1713] [INFO] Starting gunicorn 20.1.0
[2021-05-14 07:22:50 -0300] [1713] [INFO] Listening at: unix:/home/wagneroliveira/PycharmProjects/blogIntrospect/blogIntrospect.sock (1713)
[2021-05-14 07:22:50 -0300] [1713] [INFO] Using worker: sync
[2021-05-14 07:22:50 -0300] [1766] [INFO] Booting worker with pid: 1766
[2021-05-14 07:22:50 -0300] [1775] [INFO] Booting worker with pid: 1775
[2021-05-15 12:27:10 -0300] [1713] [INFO] Handling signal: term
[2021-05-15 12:27:10 -0300] [1775] [INFO] Worker exiting (pid: 1775)
[2021-05-15 12:27:10 -0300] [1766] [INFO] Worker exiting (pid: 1766)
[2021-05-15 12:27:11 -0300] [1713] [INFO] Shutting down: Master
[2021-05-17 07:44:27 -0300] [1684] [INFO] Starting gunicorn 20.1.0
[2021-05-17 07:44:27 -0300] [1684] [INFO] Listening at: unix:/home/wagneroliveira/PycharmProjects/blogIntrospect/blogIntrospect.sock (1684)
[2021-05-17 07:44:27 -0300] [1684] [INFO] Using worker: sync
[2021-05-17 07:44:27 -0300] [1807] [INFO] Booting worker with pid: 1807
[2021-05-17 07:44:27 -0300] [1845] [INFO] Booting worker with pid: 1845
